name: Unit Test and Static Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    paths-ignore:
      - README.md
      - SECURITY.md
      - docs/**
      - .github/**
      - src/env.example
    branches:
      - master
  workflow_dispatch:

jobs:
  linting-job:
    name: Linting Checks
    runs-on: ubuntu-latest
    steps:
      - run: env

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "12.x"

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"

      - name: Cache Node packages
        id: ubuntu-node-cache
        uses: actions/cache@v3
        with:
          path: src/node_modules
          key: ${{ runner.os }}-ubuntu-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install Node packages
        if: steps.ubuntu-node-cache.outputs.cache-hit != 'true'
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: pushd src && yarn install --frozen-lockfile

      - name: Run Lint Checks
        run: yarn lint
        working-directory: src
